// DO NOT EDIT THIS FILE.
import { LazyExoticComponent, ComponentType } from 'react';
import codegen from 'codegen.macro';

interface WidgetMap<T = unknown> {
  [packageName: string]: LazyExoticComponent<ComponentType<T>>;
}

/* eslint-disable @typescript-eslint/no-unsafe-return */
function getWidgetMap(): WidgetMap {
  // We inlined a require into a function since otherwise Webpack was optimizing out the unused import.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars, @typescript-eslint/no-var-requires
  const { lazy } = require('react');

  // This defines the `widgetMap`.
  codegen`
  const path = require('path');
  const { getModularRoot, generateWidgetMap } = require('modular-scripts');

  const widgetMap = generateWidgetMap(
    path.join(getModularRoot(), 'packages')
  );
  
  module.exports = 'const widgetMap = ' + widgetMap + ';';
  `;

  // eslint-disable-next-line @typescript-eslint/ban-ts-comment,
  // @ts-ignore
  return widgetMap;
}
/* eslint-enable @typescript-eslint/no-unsafe-return */

// Given a directory of widgets, generate and export a widget map, like:
//
// export default {
//   'package-name': lazy(() => import('package-name'))
// }
export default getWidgetMap();
