// DO NOT EDIT THIS FILE.
/* eslint-disable import/no-extraneous-dependencies, no-unused-vars */
import { lazy } from 'react';
import codegen from 'codegen.macro';
/* eslint-enable import/no-extraneous-dependencies, no-unused-vars */

function getWidgetMap() {
  // This defines the `widgetMap`.
  codegen`
  const path = require('path');
  const { getModularRoot, generateWidgetMap } = require('modular-scripts');

  const widgetMap = generateWidgetMap(
    path.join(getModularRoot(), 'widgets')
  );
  
  module.exports = 'const widgetMap = ' + widgetMap + ';';
  `;

  // eslint-disable-next-line no-undef
  return widgetMap;
}

// Given a directory of widgets, generate and export a widget map, like:
//
// export default {
//   'package-name': lazy(() => import('package-name'))
// }
export default getWidgetMap();
