import * as fs from 'fs-extra';
import * as path from 'path';

interface PackageJson {
  name: string;
  private?: boolean;
}

// Given a directory of widgets, generate a map like:
// { 'package-name': lazy(() => import('package-name')) }
export default function generateComponentImports(
  widgetsDirectoryPath: string,
): string {
  const packageNames = fs
    .readdirSync(widgetsDirectoryPath, { withFileTypes: true })
    // Get individual widget directories.
    .filter((entry) => entry.isDirectory())
    // Get widget `package.json`s.
    .map(
      (dir) =>
        fs.readJSONSync(
          path.join(widgetsDirectoryPath, dir.name, 'package.json'),
        ) as PackageJson,
    )
    // Remove widgets which are marked as private (and therefore are not published yet.)
    .filter((packageJson) => packageJson.private !== true)
    // Get package names.
    .map((packageJson) => packageJson.name);

  return `// DO NOT EDIT THIS FILE.
${packageNames.length > 0 ? `import { lazy } from 'react';` : ''}

export default {
  ${packageNames
    .map(
      (packageName) => `'${packageName}': lazy(() => import('${packageName}'))`,
    )
    .join(',\n  ')}
}
`;
}
