import * as fs from 'fs-extra';
import { pascalCase as toPascalCase } from 'pascal-case';

// given a path, generate a map like { name: () => import(name) }
export default function scriptContent(dirPath: string): string {
  const dirs = fs
    .readdirSync(dirPath, { withFileTypes: true })
    .filter((entry) => entry.isDirectory());

  // todo - read from meta.json inside these folders and filter out those which aren't ready to be published yet
  return `// DO NOT EDIT THIS FILE.
${dirs.length > 0 ? `import {lazy} from 'react';` : ''}
export default {
  ${dirs
    .map(
      (dir) =>
        `'${toPascalCase(dir.name)}': lazy(() => import('${toPascalCase(
          dir.name,
        )}'))`,
    )
    .join(',\n  ')}
}
`;
}
